#-------------------------------
# General Site Settings
url: https://fdcl.engineering.gwu.edu
baseurl: 


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/page/:num"


#-------------------------------
# Collections
collections:
  pages:
    output: true
    permalink: /:name
  news:
    output: true
    permalink: /news/:slug
  posts:
    output: true
    permalink: /:slug
  members:
    output: true
    permalink: /members/:name

# Pages Path
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "members"
    values:
      layout: "member"


sass:
  style: compressed
